import { writeFile } from "fs/promises";
import { execSync } from "child_process";
import { prisma } from "@/lib/prisma";
import { logger } from "@/lib/logger";

const PORT_MAP_FILE = "/etc/nginx/conf.d/clawdeploy-ports.conf";

/**
 * Regenerate the Nginx port map file from all running instances in the database,
 * then reload Nginx to apply changes.
 *
 * The map file format:
 * ```nginx
 * map $instance_id $clawdeploy_port {
 *   default 0;
 *   "clxxxxxxxxxx" 12345;
 *   "clyyyyyyyyyyy" 12346;
 * }
 * ```
 */
export async function updateNginxPortMap(): Promise<void> {
  try {
    // Get all running instances with port mappings
    const instances = await prisma.instance.findMany({
      where: {
        status: "running",
        port: { not: null },
      },
      select: {
        id: true,
        port: true,
      },
    });

    // Generate map entries
    const entries = instances
      .filter((i) => i.port !== null)
      .map((i) => `  "${i.id}" ${i.port};`)
      .join("\n");

    const mapContent = `# Auto-generated by ClawDeploy — do not edit manually
map $instance_id $clawdeploy_port {
  default 0;
${entries}
}
`;

    // Write the map file
    await writeFile(PORT_MAP_FILE, mapContent, "utf-8");

    // Reload Nginx
    execSync("sudo nginx -s reload", { timeout: 5000 });

    logger.info(
      { instanceCount: instances.length },
      "Nginx port map updated and reloaded",
    );
  } catch (error) {
    logger.error({ err: error }, "Failed to update Nginx port map");
    throw error;
  }
}
